<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$isModuleEnable = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/general/enable_buynow');
$hideCart = $this->helper(Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/advance/hide_add_to_cart');
$magentoVersion = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getMagentoVersion();
$flag = 1;
if ($isModuleEnable) :
    if (version_compare($magentoVersion, '2.3.0', '<') && !$hideCart): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Sparsh_BuyNow/js/buy-now-button": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
    $config   = $this->_getConfig();
} else {
    $config   = $this->getData('config');
    $products = $this->getData('products');
}
$_helper         = $this->helper('Magento\Catalog\Helper\Output');
$_config         = $this->helper('Sm\Market\Helper\Data');
$homeStyle       = $_config->getThemeLayout('home_style');
$viewMode        = 'grid';
$image           = 'category_page_grid';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore   = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark        = $type_loadmore ? ' ltabs-mark ' : '';

$nb_type_show = $config['type_show'];

$nb_rows = 1;
$i       = 0;
$count   = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
if (count($products)) {
    ?>
    <div class="<?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            ?>
            <?php foreach ($products as $_product):
                $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<div class="item product product-item ' . $cls_mark . '">' : '</div><div class="item product product-item ' . $cls_mark . '">' ?>
                <div class="item">
                        <div class="p_box">
                          <h6 class="pdct_h6"><?= $block->escapeHtml($_product->getSku()) ?></h6>
                          <h5><a href="<?= /* @escapeNotVerified */
                               $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */
                                $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a></h5>
                          <h5 class="price"><?= /* @escapeNotVerified */
                        $block->getProductPrice($_product) ?><a href="javascript:void(0)">Quick View</a></h5>
                         <div class="product_img1"><?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?><?php // Product Image
                    ?>
                    <a href="<?= /* @escapeNotVerified */
                    $_product->getProductUrl() ?>">
                        <?= $productImage->toHtml() ?>
                    </a><a class="btn zoomLink1" data-toggle="modal" data-target="#myModal"><i class="fa fa-search-plus"></i></a></div>
                    <div class="product actions product-item-actions"<?= /* @noEscape */ strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= /* @noEscape */ strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= /* @noEscape */ $block->escapeHtml($_product->getSku()) ?>"
                                              action="<?= /* @noEscape */ $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_product) ?>"
                                              id="product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
                                              method="post">
                                            <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php if ($isModuleEnable):
                                                $buttonTitle = $this->helper("Sparsh\BuyNow\Helper\Data")->getConfig('buynow/advance/button_title');?>
                                                <button type="submit"
                                                        title="<?= /* @noEscape */ $block->escapeHtml(__($buttonTitle)); ?>"
                                                        class="action primary sparsh-buynow-button"
                                                        data-mage-init='
                                                        {
                                                            "Sparsh_BuyNow/js/buy-now": {
                                                                "form": "#product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
                                                            }
                                                        }'
                                                >
                                                    <i class="fa fa-cart-plus"></i><span><?= /* @noEscape */ __($buttonTitle) ?></span>
                                                </button>
                                            <?php endif; ?>
                                            <?php if ($isModuleEnable ? ($hideCart ? $flag = 0 : $flag) : $flag): ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary<?= /* @noEscape */ $isModuleEnable ? ' sparsh-buynow-custom-tocart' : '' ?>"
                                                >
                                                    <i class="fa fa-cart-plus"></i><span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif; ?>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @noEscape */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @noEscape */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                      <hr/>
                      <div class="hvr_links">
  <a href="" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
  <i class="fa fa-heart-o"></i>Wishlist</a>
  <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
  <a href="" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
  <i class="fa fa-clone"></i>Compare</a>
  <a href="javascript:void(0)"><i class="fa fa-archive"></i>Favorite</a>
</div>
                    </div>
                        </div>
                      </div>
                <?php echo ($iterator == count($products) + 1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php } else {
    if (!$this->_isAjax()) { ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php }
} ?>