<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
    $config   = $this->_getConfig();
} else {
    $config   = $this->getData('config');
    $products = $this->getData('products');
}
$_helper         = $this->helper('Magento\Catalog\Helper\Output');
$_config         = $this->helper('Sm\Market\Helper\Data');
$homeStyle       = $_config->getThemeLayout('home_style');
$viewMode        = 'grid';
$image           = 'category_page_grid';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore   = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark        = $type_loadmore ? ' ltabs-mark ' : '';

$nb_type_show = $config['type_show'];

$nb_rows = 1;
$i       = 0;
$count   = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
if (count($products)) {
    ?>
<?php $iterator = 1; ?>
    <div class="row special_section">
        <div class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            ?>
            <?php foreach ($products as $_product):
                $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
            ?>
            <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<div class="item product product-item ' . $cls_mark . '">' : '</div><div class="item product product-item ' . $cls_mark . '">' ?>
            <div class="col-md-6 spe_detials">
               <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */
                               $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */
                                $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                <?= /* @escapeNotVerified */
                    $block->getProductPrice($_product) ?>
                    <?= $block->getProductDetailsHtml($_product) ?>
                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                              action="<?= /* @NoEscape */
                                              $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product"
                                                   value="<?= /* @escapeNotVerified */
                                                   $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */
                                            Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @escapeNotVerified */
                                                   $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                            <span><?= /* @escapeNotVerified */
                                                __('Order Now') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */
                                                    __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                    __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                    </div>
          </div>
            <div class="col-md-6 spe_img">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image
                    ?>
                    <div class="image-grid">
                        <a href="<?= /* @escapeNotVerified */
                        $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                    </div>
            </div>
            <?php echo ($iterator == count($products) + 1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php } else {
    if (!$this->_isAjax()) { ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php }
} ?>