<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Sr no')) ?></th>

                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Prduct Details')) ?></th>
                    <!--<th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>-->
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>

                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>


                    <th scope="col" class="col status status-lable"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php $count = 1; ?>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Sr no')) ?>" class="col id"><?=$count?><?= $block->escapeHtml($_order->getRealId()) ?></td>


                        <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="col id">
                            Order Id : <?= $block->escapeHtml($_order->getRealOrderId()) ?>
                        
                             <ul class="order__items-list"><?php
                            foreach ($_order->getAllVisibleItems() as $_item) {
                                echo "<li>". $block->escapeHtml($_item->getName())."</li>";
                            } 
                            ?></ul>

                            <span class="item__total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></span><br>

                            Order Date:<?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>

                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        
                       <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="col shipping"><?php
                         $shippingAddress = $_order->getShippingAddress();
                         if($shippingAddress){
                            $name = $shippingAddress->getName();
                            $state = $shippingAddress->getRegion();
                            $company = $shippingAddress->getCompany();
                            $shippingcity = $shippingAddress->getCity();
                            $shippingstreet = $shippingAddress->getStreet();
                            $shippingpostcode = $shippingAddress->getPostcode();      
                            $shippingtelephone = $shippingAddress->getTelephone();
                            $shippingstate_code = $shippingAddress->getRegionCode();
                            $countryCode = $shippingAddress->getCountryId();
                            ?>
                            <ul>
                                <li><?=$name.','?></li>
                                <?=$company ? '<li>'.$company.',</li>' : ''?>
                                <li><?=$shippingstreet[0].(isset($shippingstreet[1]) ? $shippingstreet[1] : '').','?></li>
                                <li><?=$shippingcity.($state ? ', '.$state : '').', '.$countryCode.'-'.$shippingpostcode.','?></li>
                                <li><?=$shippingtelephone?></li>
                            </ul>
                            <?php
                         }else{
                            echo '&nbsp;';
                         }
                        ?>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="col status">
                            <?php $status = $_order->getStatus();?>
                            <?php if ($status == 'canceled' || $status == 'closed'):?>
                                <ul class="order-timeline">
                                    <li><?= $block->escapeHtmlAttr(__($_order->getStatusLabel())) ?></li>
                                </ul>
                            <?php else: ?>
                                <ul class="order-timeline">
                                    <li <?=($status == 'new' || $status == 'pending' ? 'class="selected"' : '')?>>Ordered </li>
                                    <li class="down-arrow"><span><i class="fa fa-arrow-down" aria-hidden="true"></i></span></li>
                                    <li <?=($status == 'processing' ? ' class="selected"' : '')?>>Processing </li>
                                    <li class="down-arrow"><span><i class="fa fa-arrow-down" aria-hidden="true"></i></span></li>
                                    <li <?=($status == 'complete' ? ' class="selected"' : '')?>>Delivered </li>
                                </ul>
                            <?php endif;?>
                        </td>

                        <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                            <ul class="actions-list">
                                <li>    
                                    <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                        <i class="fa fa-eye" aria-hidden="true"></i><span><?= $block->escapeHtml(__('View')) ?></span>
                                    </a>
                                </li>
                                <?php if ($_order->canCancel()) : ?>
                                    <li>
                                        <a href="<?= $this->getUrl('cancelorder/order/cancel').'?order_id='.$_order->getEntityId(); ?>" class="action cancel_order">
                                            <i class="fa fa-window-close-o" aria-hidden="true"></i><span><?= ('Cancel') ?></span>    
                                        </a>
                                    </li>
                                <?php endif ?>
                                <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                    <li>
                                        <a href="#" data-post='<?= /* @noEscape */
                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                            ->getPostData($block->getReorderUrl($_order))
                                        ?>' class="action order">
                                            <i class="fa fa-cart-plus" aria-hidden="true"></i><span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                        </a>
                                    </li>
                                <?php endif ?>
                                <li>
                                    <a href="#" data-post='<?= /* @noEscape */
                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                            ->getPostData($block->getReorderUrl($_order))
                                        ?>' class="action return-replace">
                                            <i class="fa fa-repeat" aria-hidden="true"></i><span><?= $block->escapeHtml(__('Return & Replace')) ?></span>
                                    </a>
                                </li>
                            </ul>
                        </td>
                    </tr>
                    <?php $count++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
<?php endif ?>

<div class="confirmation-popup"></div>