<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode        = 'grid';
    $image           = 'category_page_grid';
    $showDescription = true;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showWishlist    = true;
    $showCompare     = true;
    $showCart        = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos    = $block->getPositioned();
    $tag_id = "sm_filterproducts_" . time() . rand() . "";
    ?>

    <div id="<?php echo $tag_id; ?>" class="block products-sidebar">
        <?php
        if ($this->_getConfig('product_source') == 'countdown_products') {
            $dateTo = $this->_getConfig('date_to', '');
            ?>
            <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
                <div class="deals-time time-day">
                    <div class="num-time"></div>
                    <div class="title-time"></div>
                </div>
                <div class="deals-time time-hours">
                    <div class="num-time"></div>
                    <div class="title-time"></div>
                </div>
                <div class="deals-time time-mins">
                    <div class="num-time"></div>
                    <div class="title-time"></div>
                </div>
                <div class="deals-time time-secs">
                    <div class="num-time"></div>
                    <div class="title-time"></div>
                </div>
            </div>
        <?php } ?>

        <div class="block-content block-content-products">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <div class="item product product-item">
                    <div class="item-inner clearfix">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>

                        <?php // Product Image ?>
                        <div class="box-image">
                            <a href="<?php /* @escapeNotVerified */
                            echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                        </div>

                        <div class="product details product-item-details box-info">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
                                   echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            <?php echo $block->getProductDetailsHtml($_product); ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }       
        </script>
    <?php endif; ?>
<?php endif; ?>
