<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode        = 'grid';
    $image           = 'category_page_grid';
    $showDescription = false;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showWishlist    = true;
    $showCompare     = true;
    $showCart        = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos    = $block->getPositioned();
    $tag_id = "sm_filterproducts_" . time() . rand() . "";
    ?>
    <div id="<?php echo $tag_id; ?>" class="block products-single">
        <div class="block-content block-content-products products-grid">
            <div class="f-left">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $i=1; foreach ($_productCollection as $_product): ?>
                <div class="s_box_top<?php echo $i++; ?>">
                    <div class="top_r">
                         <h6 class="h20">Special items</h6>
                        <ul class="icon_link">
                            <li><?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                              action="<?= /* @NoEscape */
                                              $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product"
                                                   value="<?= /* @escapeNotVerified */
                                                   $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */
                                            Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @escapeNotVerified */
                                                   $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="spe_btn"><i class="fas fa-shopping-cart"></i>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */
                                                    __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                    __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?></li>
                            <li><a href="" class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */
                                               echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist" role="button"><i class="far fa-heart"></i>
                                            </a></li>
                            <li><?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?><a href="" class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $compareHelper->getPostDataParams($_product); ?>' role="button"><i class="fas fa-retweet"></i>
                                        </a></li>
                            <li><a href="javascript:void(0)"><i class="fas fa-toolbox"></i></a></li>
                        </ul>
                    </div>
                    <div class="mddl_r">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <div class="box-image">
                            <a href="<?php /* @escapeNotVerified */
                            echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                        </div>
                    </div>
                    <div class="bttm_r">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h4>
                        <a href="<?php /* @escapeNotVerified */
                                   echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                        </a>
                        </h4>
                        <h6>
                            <?php /* @escapeNotVerified */
                            echo $block->getProductPrice($_product) ?>
                        </h6>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        
        
        </script>
    <?php endif; ?>
<?php endif; ?>

