<?php /** @var $block \Magento\Catalog\Block\Product\View */ ?>
<?php
$isModuleEnable = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/general/enable_buynow');
$hideCart = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/advance/hide_add_to_cart');
$flag = 1;
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
<div class="box-tocart">
    <div class="fieldset">
        <div class="field qty">
            <div class="control">
                       <div class="control-qty">
                       <p>Quantity</p>
                            <span class="quantity-controls1 quantity-plus1"><i class="fa fa-angle-up custom" ></i></span>
                            <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?= /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @noEscape */ __('Qty') ?>"
                       class="qty-default input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                            <span class="quantity-controls1 quantity-minus1"><i class="fa fa-angle-down custom" ></i></span>

                            <script type="text/javascript">
                                require([
                                    'jquery'
                                ], function ($) {
                                    $('.quantity-minus1').click(function () {
                                        $('.qty-default').val(Number($('.qty-default').val()) + 1);
                                    });

                                    $('.quantity-plus1').click(function () {
                                        var value = Number($('.qty-default').val()) - 1;
                                        if (value > 0) {
                                            $('.qty-default').val(value);
                                        }

                                    });
                                });
                            </script>
                        </div>
            </div>
        </div>
        <div class="actions">
            <?php if ($isModuleEnable ? ($hideCart ? $flag = 0 : $flag) : $flag) : ?>
                <button type="submit"
                        title="<?= /* @noEscape */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @noEscape */ $buttonTitle ?></span>
                </button>
            <?php endif; ?>
            <?php if ($isModuleEnable) :
                $buttonTitle = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/advance/button_title'); ?>
                <div class="sparsh-buynow-view">
                    <button type="submit"
                            title="<?= /* @noEscape */ __($buttonTitle) ?>"
                            class="action primary"
                            id="product-sparsh-buynow-button"
                            data-mage-init='
                            {
                                "Sparsh_BuyNow/js/buy-now":
                                {
                                    "form": "#product_addtocart_form"
                                }
                            }
                            '>
                    <span><?= /* @noEscape */ __($buttonTitle) ?></span>
                    </button>
                </div>
            <?php endif; ?>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>