<?php /** @var $block \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart */ ?>
<?php
$isModuleEnable = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/general/enable_buynow');
$hideCart = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/advance/hide_add_to_cart');
$flag = 1;
?>
<?php
/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();
?>
<?php foreach ($block->getChildNames() as $childName) : ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
            <div class="field qtyw">
                <div class="control">
                    <input type="number" data-role="qty" id="wish-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty" class="input-text qty" data-validate="{'required-number':true,'validate-greater-than-zero':true, 'validate-item-quantity':{'minAllowed':<?= /* @noEscape */ $allowedQty['minAllowed'] ?>,'maxAllowed':<?= /* @noEscape */ $allowedQty['maxAllowed'] ?>}}"
                           name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" value="<?= /* @noEscape */ (int)($block->getAddToCartQty($item) * 1) ?>" <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?>>
                           <span class="quantity-controls1 quantity-plus<?= $block->escapeHtmlAttr($item->getId()) ?>"><i class="fa fa-angle-down custom"></i></span>
                           <span class="quantity-controls2 quantity-minus<?= $block->escapeHtmlAttr($item->getId()) ?>"><i class="fa fa-angle-up custom"></i></span>
                               <script type="text/javascript">
                                require([
                                    'jquery'
                                ], function ($) {
                                    $('.quantity-minus<?= $block->escapeHtmlAttr($item->getId()) ?>').click(function () {
                                        $('#wish-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty').val(Number($('#wish-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty').val()) + 1);
                                    });

                                    $('.quantity-plus<?= $block->escapeHtmlAttr($item->getId()) ?>').click(function () {
                                        var value = Number($('#wish-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty').val()) - 1;
                                        if (value > 0) {
                                            $('#wish-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty').val(value);
                                        }

                                    });
                                });
                            </script>
                </div>
            </div>
        <?php if ($product->isSaleable()): ?>
            <div class="product-item-actions">
                <div class="actions-primary">
                    <?php if ($isModuleEnable ? ($hideCart ? $flag = 0 : $flag) : $flag): ?>
                        <button type="button"
                                data-role="tocart"
                                data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>'
                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>"
                                class="action tocart primary<?= /* @noEscape */ $isModuleEnable ? ' sparsh-buynow-custom-tocart' : '' ?>">
                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                        </button>
                    <?php endif; ?>
                    <?php if ($isModuleEnable):
                        $buttonTitle = $this->helper("Sparsh\BuyNow\Helper\Data")->getConfig('buynow/advance/button_title');?>
                        <button type="button"
                                data-role="tocart"
                                data-post='<?= /* @noEscape */ $this->helper("Sparsh\BuyNow\Helper\WishlistData")->getAddToCartParams($item) ?>'
                                title="<?= /* @noEscape */ __($buttonTitle) ?>"
                                data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>"
                                class="action primary sparsh-buynow-button">
                            <i class="fas fa-shopping-cart"></i><span><?= /* @noEscape */ __($buttonTitle) ?></span>
                        </button>
                    <?php endif; ?>
                </div>
            </div>
        <?php else: ?>
            <?php if ($product->getIsSalable()): ?>
                <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                </p>
            <?php else: ?>
                <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </fieldset>
</div>
