<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$isModuleEnable = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/general/enable_buynow');
$hideCart = $this->helper(Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/advance/hide_add_to_cart');
$magentoVersion = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getMagentoVersion();
$flag = 1;
if ($isModuleEnable) :
    if (version_compare($magentoVersion, '2.3.0', '<') && !$hideCart): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Sparsh_BuyNow/js/buy-now-button": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Market\Helper\Data');
$homeStyle          = $_config->getThemeLayout('home_style');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="toolbar-top">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode        = 'grid';
        $image           = 'category_page_grid';
        $showDescription = false;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode        = 'list';
        $image           = 'category_page_list';
        $showDescription = true;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-product products wrapper <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>

        <?php if ($viewMode == 'grid') { ?>
            <ol class="products list items product-items row">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info innerPagethumb" data-container="product-<?= /* @escapeNotVerified */
                        $viewMode ?>">
                        <div class="innerPagethumb_top">
                        <div class="dtlsT">
                            <table class="table dtlsTbl">
                                <tbody>
                                    <tr>
                                        <td>Size</td>
                                        <td> : 1220 X 2440 mm</td>
                                    </tr>
                                    <tr>
                                      <td>Color</td>
                                      <td> : Clear (S-000)</td>
                                    </tr>
                                    <tr>
                                      <td>Texture</td>
                                      <td> : Glossy</td>
                                    </tr>
                                    <tr>
                                      <td>Brand</td>
                                      <td> : Yearlong</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <div class="innerPagethumb_img"><?= $productImage->toHtml() ?><a class="btn zoomLink2" data-toggle="modal" data-target="#myModal"><i class="fa fa-search-plus"></i></a></div>
                        </div>
                        <div class="innerPagethumb_mddl">
                            <div class="top-mddl">
                                <h6>Availability<span>: <?php if ($_product->isAvailable()): ?>
                                <?= /* @escapeNotVerified */
                                __('In stock') ?>
                                <?php else: ?>
                                <?= /* @escapeNotVerified */
                                __('Out of stock') ?>
                                <?php endif; ?></span></h6>
                                <h4><?= /* @escapeNotVerified */
                                $block->getProductPrice($_product) ?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                                 ( Price inclusive of VAT )</h4>
                    <h6>Price may varies according to the payment mode</h6>
                            </div>
                            <div class="bttm-mddl">
                                <h5><?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
                                       $_product->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>   
                                </h5>
                                <p>Product Code:<?= $block->escapeHtml($_product->getSku()) ?></p>
                            </div>
                        </div>
                            <div class="product details product-item-details">
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                      action="<?= /* @NoEscape */
                                                      $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?= /* @escapeNotVerified */
                                                           $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */
                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @escapeNotVerified */
                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <?php if ($isModuleEnable):
                                                $buttonTitle = $this->helper("Sparsh\BuyNow\Helper\Data")->getConfig('buynow/advance/button_title');?>
                                                <button type="submit"
                                                        title="<?= /* @noEscape */ $block->escapeHtml(__($buttonTitle)); ?>"
                                                        class="action primary sparsh-buynow-button"
                                                        data-mage-init='
                                                        {
                                                            "Sparsh_BuyNow/js/buy-now": {
                                                                "form": "#product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
                                                            }
                                                        }'
                                                >
                                                    <span><?= /* @noEscape */ __($buttonTitle) ?></span>
                                                </button>
                                            <?php endif; ?>
                                            <?php if ($isModuleEnable ? ($hideCart ? $flag = 0 : $flag) : $flag): ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart1 primary<?= /* @noEscape */ $isModuleEnable ? ' sparsh-buynow-custom-tocart' : '' ?>"
                                                >
                                                    <span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif; ?>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */
                                                            __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                            __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                                            <?= /* @escapeNotVerified */
                                            $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= /* @escapeNotVerified */
                                            $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                            $_productNameStripped ?>"
                                               class="action more"><?= /* @escapeNotVerified */
                                                __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div data-role="add-to-links"
                                             class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <div class="actionBox">
                                            <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#" class="action towishlist"
                                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist" role="button">
                                                            <i class="fa fa-heart-o"></i>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>
                                                <a href="javascript:void(0)"><i class="fa fa-archive"></i></a>
                                                <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */
                                                   echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                        <i class="fa fa-clone"></i>
                                                </a>
                                            <?php } ?>
                                        </div>
                                    </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php } else { ?>
            <ol class="products list items product-items">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-list">
                            <div class="item-inner">
                                <div class="box-image-list">
                                    <?php $productImage = $block->getImage($_product, $image); ?>

                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?php echo $productImage->toHtml(); ?>
                                    </a>

                                </div>

                                <div class="product details product-item-details box-info-list">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <h2 class="product name product-item-name product-name">
                                        <a class="product-item-link" href="<?php /* @escapeNotVerified */
                                        echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </h2>

                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php /* @escapeNotVerified */
                                    echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <div class="product-item-inner">
                                        <?php if ($showDescription): ?>
                                            <div class="product description product-item-description">
                                                <?php /* @escapeNotVerified */
                                                echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php /* @escapeNotVerified */
                                                echo $_product->getProductUrl() ?>"
                                                   title="<?php /* @escapeNotVerified */
                                                   echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */
                                                    echo __('Learn More') ?></a>
                                            </div>
                                        <?php endif; ?>
                                    </div>

                                    <div class="bottom-action">
                                        <?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */
                                                    echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart btn-action btn-cart">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                            echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
                                                            echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php } ?>

                                        <div class="add-to-links" data-role="add-to-links" class="actions-secondary">
                                            <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#" class="action towishlist btn-action link-wishlist"
                                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist" role="button">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>

                                            <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare btn-action link-compare"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */
                                                   echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php } ?>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
